import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "You Can WIN",
    author: "Shiv Khera",
    image:"https://5.imimg.com/data5/SELLER/Default/2020/10/ZB/JR/SC/113288716/11-06-2020-jpg.jpg",
    price: "5000",
    rating:"4.4",
    categoryName: "non-fiction",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    image:"https://pollycastor.com/wp-content/uploads/2020/03/IMG_2429.jpg",
    price: "140",
    rating:"3.6",
    categoryName: "non-fiction",
  },
  {
    _id: uuid(),
    title: "House of Leaves",
    author: "Mark Z. Danielewski",
    image:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1403889034i/24800.jpg",
    price: "707",
    rating:"5.0",
    categoryName: "horror",
  },
 
  {
    _id: uuid(),
    title: "Murder on the Orient Express",
    author: "Agatha Christie",
    image:"https://m.media-amazon.com/images/I/81SoIAzWbnL._AC_UF1000,1000_QL80_.jpg",
    price: "259",
    rating:"4.6",
    categoryName: "mystery",
  },
  {
    _id: uuid(),
    title: "Grimms' Fairy Tales",
    author: "Jacob Grimm",
    image:"https://images-cdn.ubuy.co.in/63953075ad04f72c4343e802-an-illustrated-treasury-of-grimm-s-fairy.jpg",
    price: "250",
    rating:"3.8",
    categoryName: "fairy tales",
  },
  {
    _id: uuid(),
    title: "Nineten Eighty-four",
    author: "George Orwell",
    image:"https://m.media-amazon.com/images/I/41wBPTEJ5gL.jpg",
    price: "145",
    rating:"5.0",
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    title: "Gone Girl",
    author: "Gillian Flynn",
    image:"https://m.media-amazon.com/images/I/71+khXHbe5L._AC_UF1000,1000_QL80_.jpg",
    price: "278",
    rating:"4.9",
    categoryName: "mystery",
  },
  {
    _id: uuid(),
    title: "Jerome K Jerome Omnibus",
    author: "Jerome Klapka Jerome",
    image:"https://m.media-amazon.com/images/I/71LCYluJhLL._AC_UF1000,1000_QL80_.jpg",
    price: "190",
    rating:"3.5",
    categoryName: "humour",
  },
  {
    _id: uuid(),
    title: "The Rise and Fall of the Third Reich",
    author: "William L Shirer",
    image:"https://i.ytimg.com/vi/R8HClaxGUSY/sddefault.jpg",
    price: "2537",
    rating:"4.3",
    categoryName: "non-fiction",
  },
  {
    _id: uuid(),
    title: "Alice in Wonderland",
    author: "Lewis Caroll",
    image:"https://i.etsystatic.com/6908127/r/il/e02ee5/573900593/il_570xN.573900593_11xr.jpg",
    price: "89.10",
    rating:"3.7",
    categoryName: "fairy tales",
  },
  {
    _id: uuid(),
    title: "Atomic Habits",
    author: "James Clear",
    image:"https://images.meesho.com/images/products/181308553/hxby6_512.webp",
    price: "469",
    rating:"3.6",
    categoryName: "non-fiction",
  },
  {
    _id: uuid(),
    title: "Gulliver's Travels",
    author: "Jonathan Swift",
    image:"https://m.media-amazon.com/images/I/61RrjcUgL9L.jpg",
    price: "163",
    rating:"4.2",
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    title: "Sherlock Holmes Omnibus",
    author: "Sir Arthur Conan Doyle",
    image:"https://rukminim2.flixcart.com/image/850/1000/k3uhhu80/book/4/2/8/the-sherlock-holmes-omnibus-56-short-stories-and-4-novels-original-imafmvwp7nwfhcxs.jpeg?q=20",
    price: "1678",
    rating:"5.0",
    categoryName: "mystery",
  },
  {
    _id: uuid(),
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    image:"https://images.squarespace-cdn.com/content/v1/5dc21d198c1cfd4ef901f025/2488a60f-5f9a-460b-85e1-9235954325af/tale-of-two-cities-book-cover.jpeg",
    price: "219",
    rating:"4.3",
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    title: "Born a Crime",
    author: "Trevor Noah",
    image:"https://images.meesho.com/images/products/260187281/jtvdf_512.webp",
    price: "2396.96",
    rating:"4.6",
    categoryName: "humour",
  },
  {
    _id: uuid(),
    title: "Animal Farm",
    author: "George Orwell",
    image:"https://m.media-amazon.com/images/I/91LUbAcpACL._AC_UF1000,1000_QL80_.jpg",
    price: "109",
    rating:"4.2",
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    title: "Aesop's Fables",
    author: "Aesop",
    image:"https://m.media-amazon.com/images/I/61voTsTR8TL.jpg",
    price: "198",
    rating:"3.9",
    categoryName: "fairy tales",
  },
  {
    _id: uuid(),
    title: "Dark Matter",
    author: "Blake Crouch",
    image:"https://blakecrouch.com/wp-content/uploads/2022/03/BlakeCrouch-DarkMatter-3Dhardcover.png",
    price: "749",
    rating:"3.7",
    categoryName: "mystery",
  },
  {
    _id: uuid(),
    title: "A Short History of Nearly Everything",
    author: "Bill Bryson",
    image:"https://cdn.kobo.com/book-images/80c31cad-62cd-4e17-bc44-79860a0c4c5d/1200/1200/False/a-really-short-history-of-nearly-everything-1.jpg",
    price: "387",
    rating:"4.1",
    categoryName: "non-fiction",
  },
  {
    _id: uuid(),
    title: "A Confederacy of Dunces",
    author: "John Kennedy",
    image:"https://m.media-amazon.com/images/I/81vVYM9dlcL._AC_UF1000,1000_QL80_.jpg",
    price: "357.90",
    rating:"4.8",
    categoryName: "humour",
  },
];
